import {
  contractToHire,
  contractTypes,
  experienceLevels,
  featuredJobs,
  hoursToWorkPerWeek,
  oneTimeProject,
  ongoingProject,
} from "./options";

export const formDefaultValues: ITracker["filters"] = {
  trackerName: "",
  contractType: contractTypes[0].value as ITracker["filters"]["contractType"],
  minHourlyRate: null,
  maxHourlyRate: null,
  minFixedBudget: null,
  maxFixedBudget: null,
  categories: [],
  experienceLevel: experienceLevels as ITracker["filters"]["experienceLevel"],
  hoursToWorkPerWeek: hoursToWorkPerWeek[0].value,
  requiredSkills: [],
  excludedSkills: [],
  matchAllWords: [],
  matchAnyWords: [],
  excludeAnyWords: [],
  paymentMethodVerified: true,
  minClientRating: 4.5,
  minClientReviewsCount: null,
  minHireRate: 55,
  minNumOfHires: null,
  minTotalJobs: null,
  minTotalSpent: null,
  minAvgHourlyRate: null,
  countryOfClient: [],
  excludedCountryOfClient: [],
  enterpriseClients: false,
  featuredJobs: featuredJobs[0].value,
  oneTimeProject: oneTimeProject[0].value,
  ongoingProject: ongoingProject[0].value,
  contractToHireProject: contractToHire[0].value,
};
