export type FormSelectOption = { value: string; label: string };
export const contractTypes: FormSelectOption[] = [
  { value: "*", label: "Both Hourly Rate & Fixed Price" },
  { value: "Hourly", label: "Hourly Rate" },
  { value: "FixedPrice", label: "Fixed Price" },
] as const;

export const hoursToWorkPerWeek: FormSelectOption[] = [
  { value: "*", label: "Any hours per week" },
  { value: "moreThan30", label: "More than 30 Hours/week" },
  { value: "lessThan30", label: "Less than 30 Hours/week" },
] as const;

export const featuredJobs: FormSelectOption[] = [
  { value: "*", label: "Notify for both" },
  { value: "true", label: "Only notify for featured jobs" },
  { value: "false", label: "Only notify for not featured jobs" },
] as const;

export const oneTimeProject: FormSelectOption[] = [
  { value: "*", label: "Notify for both" },
  { value: "true", label: "Only notify for one-time projects" },
  { value: "false", label: "Only notify for none one-time projects" },
] as const;

export const ongoingProject: FormSelectOption[] = [
  { value: "*", label: "Notify for both" },
  { value: "true", label: "Only notify for Ongoing projects" },
  { value: "false", label: "Only notify for none Ongoing projects" },
] as const;

export const contractToHire: FormSelectOption[] = [
  { value: "*", label: "Notify for both" },
  { value: "true", label: "Only notify for Contract to hire projects" },
  { value: "false", label: "Only notify for none Contract to hire projects" },
] as const;

export const experienceLevels = ["Entry Level", "Intermediate", "Expert"];

export const categories = [
  "3D Modeling & CAD",
  "AI & Machine Learning",
  "AI Apps & Integration",
  "Accounting & Bookkeeping",
  "Art & Illustration",
  "Audio & Music Production",
  "Blockchain, NFT & Cryptocurrency",
  "Branding & Logo Design",
  "Building & Landscape Architecture",
  "Chemical Engineering",
  "Civil & Structural Engineering",
  "Community Management & Tagging",
  "Content Writing",
  "Contract Manufacturing",
  "Corporate & Contract Law",
  "Customer Service & Tech Support",
  "Data Analysis & Testing",
  "Data Entry & Transcription Services",
  "Data Extraction/ETL",
  "Data Mining & Management",
  "Database Management & Administration",
  "Desktop Application Development",
  "DevOps & Solution Architecture",
  "Digital Marketing",
  "ERP/CRM Software",
  "Ecommerce Development",
  "Editing & Proofreading Services",
  "Electrical & Electronic Engineering",
  "Energy & Mechanical Engineering",
  "Finance & Tax Law",
  "Financial Planning",
  "Game Design & Development",
  "Graphic, Editorial & Presentation Design",
  "Information Security & Compliance",
  "Interior & Trade Show Design",
  "International & Immigration Law",
  "Language Tutoring & Interpretation",
  "Lead Generation & Telemarketing",
  "Management Consulting & Analysis",
  "Market Research & Product Reviews",
  "Marketing, PR & Brand Strategy",
  "Mobile Development",
  "NFT, AR/VR & Game Art",
  "Network & System Administration",
  "Other - Accounting & Consulting",
  "Other - Software Development",
  "Performing Arts",
  "Personal & Professional Coaching",
  "Photography",
  "Physical Sciences",
  "Product Design",
  "Product Management & Scrum",
  "Professional & Business Writing",
  "Project Management",
  "Public Law",
  "QA Testing",
  "Recruiting & Human Resources",
  "Sales & Marketing Copywriting",
  "Scripts & Utilities",
  "Translation & Localization Services",
  "Video & Animation",
  "Virtual Assistance",
  "Web & Mobile Design",
  "Web Development",
] as const;

export const countries = [
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern and Antarctic Lands",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territories",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;
